name: Build

on:
  workflow_dispatch:
#   push:
#     paths-ignore:
#       - .github/**
#     branches:
#       - master
#       - develop
#       - release/**
#       - feature/**
#       - hotfix/**

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
  
jobs:
  call_job:
    name: Set Environment
    uses: ORG/DEVOPS/.github/workflows/rwf_set_environment.yml@main

  build_job:
    name: Build
    needs: [call_job]
    runs-on: windows-latest
    environment: ${{ needs.call_job.outputs.set_env }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Node install
        uses: actions/setup-node@v3
        with:
          node-version: 16.*
        
      - name: Angular install
        run: |
          npm install -g @angular/cli
          
      - name: NPM install 
        working-directory: ./sources/frontend
        run: npm install
          
      - name: Build
        working-directory: ./sources/f
        run: |
          $envName = "${{ vars.ENVIRONMENT_NAME }}"
          $envName = $envName.ToLower()
          npm run build_$envName

#        - name: Run Unit Tests
#          working-directory: ./sources/frontend
#          run: |
#            ng test --browsers=ChromeHeadless --code-coverage --watch=false

      - name: Zip
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: release.zip
          path: ${{ github.workspace }}/sources/frontend/dist/**
          directory: ${{ github.workspace }}
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: release
          path: ${{ github.workspace }}/release.zip
          
  deploy_job:
      name: Deploy
      needs: [build_job,call_job]
      runs-on: ubuntu-latest
      environment: ${{ needs.call_job.outputs.set_env }}
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || contains(github.ref,'refs/heads/release/') || contains(github.ref,'refs/heads/hotfix/') }}
      
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: release
          path: ${{ github.workspace }}
        
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: az login --service-principal -u  ${{ secrets.ID }} -p ${{ secrets.SECRET }} --tenant 12341234213421342134242134214214
      
      - run: sudo chmod -R a+rw /home/runner/.azure/
      
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2.2.10
        with:
          app-name: xxxxxx
          slot-name: ${{ vars.SLOT_NAME }}
          package: ${{ github.workspace }}/release.zip
          resource-group-name: XXXXX
          
      - uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          channel: ${{ vars.SLACK_CHANNEL }}
        if: ${{ always() && vars.ENVIRONMENT_NAME }}!

  version_tag:
    needs: deploy_job
    uses: ORG/DEVOPS/.github/workflows/rwf_version.yml@main
    if: ${{ always() }}
