name: Get version from package.json

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: package-version
        run: |
         echo "Reading package.json from ./package.json"
         PACKAGE_VERSION=$(cat sources/package.json | jq '.version' | tr -d '"')
         echo ::set-output name=current-version::$PACKAGE_VERSION
         echo $PACKAGE_VERSION
