#!/bin/sh
 
# Obtém o nome da branch atual
branch_name=$(git rev-parse --abbrev-ref HEAD)
 
# Adiciona o nome da branch à mensagem do commit
if [ -n "$branch_name" ]; then
    echo "Branch: $branch_name" >> "$1"
fi
