name: Generate Badge

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: 'TU'
      version:
        type: string
        default: 'v1.0.34'
  workflow_call:
    inputs:
      environment:
        type: string
        default: 'TU'
      version:
        type: string
        default: 'v1.0.34'

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      id-token: write
      issues: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    steps:
      - name: Checkout Script
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Generate badge
        run: node .github/script/generate_badge.js
        env:
          environment: ${{ inputs.environment }}
          version:  ${{ inputs.version }}

      - name: Checkout Repo Badges
        uses: actions/checkout@v4
        with:
          repository: ifGarcia/badge
          path: badge
          # fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      - name: List generated files
        run: ls -l

      - name: Commit and push badges to target repo
        run: |
          SVG_DIR=$(find . -path ./badge -prune -o -type f -name "*.svg" -exec dirname {} \; | uniq)
          echo "SVG directory: $SVG_DIR"
          mkdir -p badge/${SVG_DIR}
          cp -r -f $SVG_DIR/* badge/${SVG_DIR}
          cd badge
          git config user.email "githubaction@github.com"
          git config user.name "Github Action"
          git add .
          git commit -m 'Update badges'
          git push
