name: Generate Badge

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: 'TU'
      version:
        type: string
        default: 'v1.0.34'
  workflow_call:
    inputs:
      environment:
        type: string
        default: 'TU'
      version:
        type: string
        default: 'v1.0.34'

permissions:
  contents: write
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Script
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: script
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Generate badge
        run: node .github/script/generate_badge.js
        env:
          environment: ${{ inputs.environment }}
          version:  ${{ inputs.version }}

      - name: Checkout Repo Badges
        uses: actions/checkout@v4
        with:
          repository: ifGarcia/badge
          path: badge
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List generated files
        run: ls -l

      - name: Commit and push badges to target repo
        run: |
          SVG_DIR=$(find . -path ./badge -prune -o -type f -name "*.svg" -exec dirname {} \; | uniq)
          echo "SVG directory: $SVG_DIR"
          mkdir -p badge/${SVG_DIR}
          cp -r -f $SVG_DIR/* badge/${SVG_DIR}
          cd badge
          git config user.email "githubaction@github.com"
          git config user.name "Github Action"
          git add .
          git commit -m 'Update badges'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ifGarcia/badge.git
