name: Secrets RWF

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  call_cicd:
    uses: ifGarcia/githubaction/.github/workflows/rwf_cicd.yml@main
    with:
      name_app_input: NomeDoApp
    secrets: 
      CLIENTID_secrets: ${{ secrets.CLIENTID }}
      CLIENTSECRET_secrets: ${{ secrets.CLIENTSECRET }}
      VAR_SECRETA_TESTE: ${{ secrets.VAR_SECRETA_TESTE }}
