name: Secrets RWF

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  call_cicd:
    uses: ifGarcia/githubaction/.github/workflows/rwf_cicd.yml@main
    with:
      name_app_input: NomeDoApp
      # # Secrets
      # ID_secrets: ${{ secrets.CLIENTID }}
      # SECRET_secrets: ${{ secrets.CLIENTSECRET }}
    secrets:
      CLIENTID_secrets: ${{ secrets.CLIENTID }}
      CLIENTSECRET_secrets: ${{ secrets.CLIENTSECRET }}
