name: Deploy

on:
  repository_dispatch:
    types: [start-deploy]

jobs:
  deploy:
    name: Deploy para ${{ github.event.client_payload.sistema }}
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar payload recebido
        run: |
          echo "Evento: ${{ github.event.action }}"
          echo "Sistema: ${{ github.event.client_payload.sistema }}"

      - name: Simular deploy
        run: |
          echo "Iniciando deploy para ${{ github.event.client_payload.sistema }}"
          sleep 60
          echo "Deploy finalizado para ${{ github.event.client_payload.sistema }}"
