name: Deploy

on:
  repository_dispatch:
    types: [start-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Iniciar deploy
        run: |
          echo "Iniciando deploy para ${{ github.event.client_payload.sistema }}"
          sleep $((RANDOM % 10 + 5))
          echo "Deploy finalizado para ${{ github.event.client_payload.sistema }}"
