name: GIT TAG MASTER

on:
  workflow_dispatch:
  pull_request_target:
    branches: [ main ]
    types: [ closed ]

jobs:
  jobtagteste:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
#         with:
#           repository: ${{ github.repository }}
#           ref: main
      
      - name: Criar Tag
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          myString=${{ github.head_ref }}
          read lastElement <<< "${myString##*/}"
          echo "The last element is: $lastElement"
          lastElement="v$lastElement-${{ github.run_number }}"
          git tag $lastElement
          git push origin $lastElement
        
#       - name: Imprime tag oi
#         run: |
#           echo ${{ github.ref }}
#           echo ${{ github.run_number }}
#           echo "${GITHUB_HEAD_REF-${GITHUB_REF##*/}}"
#           echo $GITHUB_EVENT_PATH
#           echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}'"
#           echo ${{ github.event.pull_request.head_ref }}
#           echo ${{ github.event.head_commit.message }}
          
#       - name: "Merge pull request #18 from ifGarcia/release/ifGarcia-patch-7"
#         run: |
#           echo ${{ github.event.head_commit.message }}
#           myString="Merge pull request #18 from ifGarcia/release/ifGarcia-patch-7"
#           read lastElement <<< "${myString##*/}"
#           echo "The last element is: $lastElement"
#           lastElement="v$lastElement-${{ github.run_number }}"
#           git tag $lastElement
#           git push origin $lastElement
