name: teste if

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job_testes:
    runs-on: ubuntu-latest
    environment: DEV
#    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Ai ai aiai
      run: |
        string="${{ vars.ENVIRONMENT_VAR }}"
        echo "action_state=${string^}" >> "$GITHUB_ENV"
        echo "${{ env.action_state }}"
      #build_${{ env.action_state }}
