name: teste if

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job_testes:
    runs-on: ubuntu-latest
    environment: DEV
#    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Ai ai aiai
      run: |
        environment_build="${{ vars.ENVIRONMENT_VAR }}"
        environment_build=${environment_build,,}
        build_${environment_build}
