name: teste if

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job_testes:
    runs-on: ubuntu-latest
    environment: DEV
#    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Ai ai aiai
      run: |
        echo "oi"
        echo "build_${{ vars.ENVIRONMENT_VAR.lowercase }}"
        echo "build_${{ vars.ENVIRONMENT_VAR }}.lowercase"
        echo "build_${{ vars.ENVIRONMENT_VAR }}.lowercase()"
        ng buld_$vars.ENVIRONMENT_VAR.lowercase
        ng buld_${{ vars.ENVIRONMENT_VAR }}.lowercase
        ng buld_${{ vars.ENVIRONMENT_VAR }}.lowercase()
