name: Testes Vars

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job_windows:
    runs-on: windows-latest
    environment: DEV
    steps:
    - run: |
        $envName="${{ vars.ENVIRONMENT_VAR }}"
        $envName=$envName.ToLower()
        $envName
        echo build_$envName

  job_ubuntu:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - run: |
        environment_build="${{ vars.ENVIRONMENT_VAR }}"
        environment_build=${environment_build,,}
        ${environment_build}
        echo build_${environment_build}
#         environment_build="${{ vars.ENVIRONMENT_NAME }}"
#         environment_build=${environment_build,,}
#         ng run build_${environment_build}
