name: Matrix Strategy Include Sample

on: push

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        # The include keyword that adds a new variable
        include:
          - os: windows-latest
            node: 16
            npm: 8
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - if: ${{ matrix.npm }}
        run: npm install -g npm@${{ matrix.npm }}
        
      - run: npm --version
