name: Matrix Strategy Include Sample

on: push

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          
      - name: oi 1
        run: echo oi
        
      - name: oi 2
        run: npm --version
