name: pr_valida_tag

on:
  push:
    branches: [ "main" ]

jobs:
  job_tag:
#     if: ${{ contains(github.head_ref,'release/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Imprime tag oi
        run: |
          echo ${{ github.ref }}
          echo ${{ github.run_number }}
          echo ${{ github.head_ref }}
          echo "${GITHUB_HEAD_REF-${GITHUB_REF##*/}}"
          echo ${{ github.base_ref }}
          echo ${{ github.event.pull_request.base.ref }}
