name: pr_valida_tag

on:
  push:
    branches: [ "main" ]

jobs:
  job_tag:
#     if: ${{ contains(github.head_ref,'release/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Imprime tag
        run: |
          echo ${ github.ref }
        # echo "${GITHUB_HEAD_REF-${GITHUB_REF##*/}}"
          
          
      - name: Create Tag oi
#         if:  github.ref == 'refs/heads/main'
        run: | 
          git tag ${ github.head_ref }
        # git push origin ${ github.head_ref }
