name: pr_valida_tag

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]
#     types: [ closed ]

jobs:
  job_tag:
#     if: ${{ contains(github.head_ref,'release/') }}
    runs-on: ubuntu-latest

    steps:
#       - name: Imprime tag oi
#         run: |
#           echo ${{ github.ref }}
#           echo ${{ github.run_number }}
#           echo ${{ github.head_ref }}
#           echo "${GITHUB_HEAD_REF-${GITHUB_REF##*/}}"
#           echo ${{ github.base_ref }}
#           echo $GITHUB_EVENT_PATH
#           echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}'"
#           echo ${{ github.event.pull_request.head_ref }}
#           echo ${{ github.event.head_commit.message }}
          
      - name: "Merge pull request #18 from ifGarcia/release/ifGarcia-patch-7"
        run: |
          echo ${{ github.event.head_commit.message }}
          echo "Merge pull request #18 from ifGarcia/release/ifGarcia-patch-7" | grep -o '[^/]*$'
          myString="Merge pull request #18 from ifGarcia/release/ifGarcia-patch-7"
          read lastElement <<< "${myString##*:}"
          echo "The last element is: $lastElement"
          echo "${{ github.event.head_commit.message }}" | sed 's/#//'
          

      - name: Foi merge?
        if: github.event.pull_request.merged
        run: |
          echo "Sim"
          echo ${{ github.event.pull_request.head_ref }}
