name: pr_valida_tag

on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  job_tag:
#     if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - name: Imprime oi
        run: |
          echo "${GITHUB_HEAD_REF-${GITHUB_REF##*/}}"
