on:
  workflow_dispatch:
  workflow_call:
    inputs:
      name_app_input:
        required: true
        type: string
    secrets:
      CLIENTID_secrets:
        required: true
      CLIENTSECRET_secrets:
        required: true
      VAR_SECRETA_TESTE:
        required: true
# env:
  # CLIENTID: ${{ secrets.app-inputCLIENTID }}
  # CLIENTID: ${{ inputs.app-input }}CLIENTID
  # SECRET: ${{ inputs.app-input }}CLIENTID

jobs:
  job1:
    name: ${{ inputs.name_app_input }} - CI/CD
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Teste Secret
        run: |
          echo ${{ secrets.CLIENTID_secrets }} | sed 's/./& /g'
          echo ${{ secrets.CLIENTSECRET_secrets }} | sed 's/./& /g'
          echo ${{ secrets.VAR_SECRETA_TESTE }} | sed 's/./& /g'
