name: Teste

on:
  workflow_dispatch:
  
env:
  env: ""
  
jobs:
  job_teste:
    runs-on: ubuntu-latest
    environment: env.env

    steps:
      - name: Imprime oi
        run: |
          echo "oi"
          echo "${{ vars.ENVIRONMENT_VAR }}"
