name: Teste

on:
  workflow_dispatch:
  
jobs:
  job_teste:
    runs-on: ubuntu-latest
    environment:

    steps:
      - name: Imprime oi
        run: |
          echo "oi"
          echo "${{ vars.ENVIRONMENT_VAR }}"
