name: Teste

on:
  workflow_dispatch:
  push:
    paths:
      - '**/teste.yml'
  
jobs:
  job_teste:
    runs-on: ubuntu-latest

    steps:

      - name: Echo VAR_ACTION
        run: |
          vala="VAR_"
          valB="ACTION"
          envName=$vala$valB
          echo $envName
          echo ${{ vars.VAR_ACTION }}
          envName="vars.${envName}"
          echo $envName
        # envName="${{ ${envName} }}"
          
        # envName="${{ vars." + $envName + " }}"
        # echo "${{ vars." + $envName + " }}"
        # $envName = "${{ vars.$vala$valB }}"
        # $envName
