name: Teste

on:
  workflow_dispatch:
  
jobs:
  job_teste:
    runs-on: ubuntu-latest

    steps:

      - name: Echo VAR_ACTION
        run: |
          vala= "VAR_"
          valB= "ACTION"
          envName= $vala$valB
          echo $envName
        # $envName = "${{ vars.$vala$valB }}"
        # $envName
