name: Teste

on:
  workflow_dispatch:
  
jobs:
  "":
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: Imprime oi
        run: |
          echo "oi"
          echo "${{ vars.ENVIRONMENT_VAR }}"
