name: Print Env Vars and Secrets

on:
  workflow_dispatch:

jobs:
  print-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the other repository
      uses: actions/checkout@v2
      with:
        repository: 'ifGarcia/scripts'
        path: 'scripts'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Print environment variables and secrets
      run: |
        cd scripts
        python script.py
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}


# name: Teste

# on:
#   workflow_dispatch:
#   push:
#     paths:
#       - '**/teste.yml'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       VAR_NAME: NOME_DA_VARIAVEL

#     steps:
#       - run: |
#           VAR_NAME="${{ env.VAR_NAME }}"
#           VAR_VALUE="${{ vars[$VAR_NAME] }}"
#           echo "Valor da variável $VAR_NAME é: $VAR_VALUE"
#       # echo ${{ env.VAR_NAME }}
#       # echo ${{ vars.NOME_DA_VARIAVEL }}

#   # job_teste:
#   #   runs-on: ubuntu-latest
#   #   env:
#   #     VARIAVEL-VAR: VALOR VARIAVEL-VAR
#   #     VARIAVEL-NAME: VARIAVEL-VAR
#   #   steps:
#   #     - name: Echo VAR_ACTION
#   #       run: |
#   #         VARIAVEL-NAME="${{ env.VARIAVEL-NAME }}"
#   #         VAR_VALUE="${{ env[VARIAVEL-NAME] }}"
#   #         echo "Valor da variável $VAR_NAME é: $VAR_VALUE"
          
#   #       # vala="VAR_"
#   #       # valB="ACTION"
#   #       # envName=$vala$valB
#   #       # echo $envName
#   #       # echo ${{ vars.VAR_ACTION }}
#   #       # envName="vars.${envName}"
#   #       # ${{ $envName }}
#   #       # envName="${{ ${envName} }}"
          
#   #       # envName="${{ vars." + $envName + " }}"
#   #       # echo "${{ vars." + $envName + " }}"
#   #       # $envName = "${{ vars.$vala$valB }}"
#   #       # $envName
