name: Teste

on:
  workflow_dispatch:
  
env:
  aaaaa: ""
  
jobs:
  job_teste:
    runs-on: ubuntu-latest
    environment: ${{ env.aaaaa }}

    steps:
      - name: Imprime oi
        run: |
          echo "oi"
          echo "${{ vars.ENVIRONMENT_VAR }}"
