name: trigger_teste

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .github/**
    branches:
      - master
      - develop
      - release/**
      - feature/**
      - hotfix/**

jobs:
  job_trigger:
    environment: DEV
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo oi
