name: trigger_teste

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .github/**
    branches:
      - master
      - develop
      - release/**
      - feature/**
      - hotfix/**

jobs:
  job_windows:
    runs-on: windows-latest
    environment: DEV
    steps:
    - run: |
        $envName="${{ vars.ENVIRONMENT_VAR }}"
        $envName=$envName.ToLower()
        $envName
        echo build_$envName
