name: trigger_teste

on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature/**" ]
    paths:
      - '**'
      - '!.github/**'

jobs:
  job_trigger:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo oi
