name: trigger_teste

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - release/*
      - feature/*
      - hotfix/**
    paths-ignore:
      - .github/**


jobs:
  job_windows:
    runs-on: windows-latest
    environment: DEV
    steps:
    - run: |
        $envName="${{ vars.ENVIRONMENT_VAR }}"
        $envName=$envName.ToLower()
        $envName
        echo build_$envName
