name: upload_download

on:
  workflow_dispatch:
  
jobs:

  job_upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - run: zip -r release.zip ${{ github.workspace }}
        
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: release
          path: ${{ github.workspace }}/release.zip
          
  job_download:
      needs: [job_upload]
      runs-on: ubuntu-latest
      
      steps:
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ github.workspace }}
      
      - name: Download Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: release
          path: ${{ github.workspace }}
          
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ github.workspace }}
