name: Call Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  branch: ${{ github.head_ref || github.ref_name }}

jobs:
  job_call-workflow:
    name: ""
    uses: ifGarcia/reusable_workflow/.github/workflows/chama.yml@main
      
  job_call-workflow2:
    uses: ifGarcia/reusable_workflow/.github/workflows/recebe_var.yml@main
    with:
      var_recebe_teste: "Variavel Testes enviada por input."
      var_recebe_environment: DEV
    secrets: inherit
        
  job_imprime_vars:
    name: Imprime variaveis
    needs: [job_call-workflow]
    runs-on: ubuntu-latest
    steps:
    - name: Config
      run: |
        echo "${{ needs.job_call-workflow.outputs.outputs1-VAR_OLA }}"
